# config.yaml
elasticsearch:
  addresses:
    - https://localhost:9200
  username: "elastic"
  password: "changeme"
  ca_cert: "/path/to/ca.crt"

output:
  format: "fancy"  # fancy, plain, json, csv
  style: "dark"   # dark, light, bright, blue, double
